### PR TITLE
Reorganize main process

### LINKED ISSUE #104: Reorganize main process
`main.js` is getting long, I should split this file in multiple files, with os specificity ect...

### LINKED ISSUE #259: Monochrome tray icon
I have an .ai, I could do it myself, but if a designer passes around and want to create a white-monochrome version of the logo, I can share him the vector file.

- white version
- black version

### LINKED ISSUE #423: Some input
Great app! Clean and simple without cloud sync and all that.

On macOS, I'm dreaming of:
* keyboard shortcut to hide window: cmd+H (default in system and 99% of apps).
* monochrome tray icon(s) option (black on light, and white on dark).
* most wanted: hide tray icon option (a lot of mac users really dislike "forced" tray icons).
* a short delay (0.2 sec?) on hoover (volume button and timeline bar), would fix the "flickering" appearance.

I could make the monochrome tray icons if that would help.

### LINKED ISSUE #426: Set dock menu on macOS
If we want to remove Tray on macOSm it would be great to have this.

screen shot 2018-03-23 at 15 32 20

### LINKED ISSUE #428: Can't hide application on macOS
All applications in macOS are hidden with the shortcut cmd + H, and this app seems to be the only exception... It's pretty annoying.

### PR DESCRIPTION
**Pull request by KeitIG**
Not perfect, but better.

Fix #104 
Fix #259 
Fix #423 
Fix #426 
Fix #428 

screen shot 2018-03-23 at 15 07 08

screen shot 2018-03-23 at 15 32 20

### CODE REVIEW

File: src/main-process/modules/tray.js [hunk 1]
```diff
@@ -1,14 +1,31 @@
...
+const { IPC_PLAYER_ACTION } = require('../../shared/constants/ipc');
+
+
+class TrayManager extends ModuleWindow {
+  constructor(window) {
+    super(window);
+  }
+
+  load() {
+    const appRoot = path.resolve(__dirname, '../../..'); // Maybe a better way to know this?
```
Comment (YurySolovyov) [inline src/main-process/modules/tray.js]: Not sure how much better that would be, but we might have a `paths` module with all commonly accessed paths pre-computed.

File: src/main-process/utils.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  // check if the browser window is offscreen
+  const display = electron.screen.getDisplayNearestPoint(bounds).workArea;
+
+  const onScreen = bounds.x >= display.x
+        && bounds.x + bounds.width <= display.x + display.width
+        && bounds.y >= display.y
+        && bounds.y + bounds.height <= display.y + display.height;
+
+  if(!onScreen) {
+    delete bounds.x;
```
Comment (YurySolovyov) [inline src/main-process/utils.js]: I think V8 does not like removing props like this.
It might be better to construct a new object instead.
Besides, this would avoid mutating the function argument, which makes it easier to reason about.

File: src/shared/constants/ipc.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+module.exports.IPC_APP_CLOSE = 'IPC_APP_CLOSE';
+module.exports.IPC_PLAYER_ACTION = 'IPC_PLAYER_ACTION';
+module.exports.IPC_TL_CONTEXTMENU_REPLY = 'IPC_TL_CONTEXTMENU_REPLY';
```
Comment (YurySolovyov) [inline src/shared/constants/ipc.js]: Object literal?

File: src/ui/actions/AppActions.js [hunk 4]
```diff
@@ -53,14 +55,16 @@ const init = () => {
...
   });
 
   // Listen for main-process events
-  ipcRenderer.on('playerAction', (event, reply) => {
+  ipcRenderer.on(IPC_PLAYER_ACTION, (event, reply) => {
     switch(reply) {
       case 'play':
-        PlayerActions.play();
+        // Scenarion: click on the Tray when the player is in 'stop' mode
+        if (!Player.getSrc()) PlayerActions.start();
```
Comment (YurySolovyov) [inline src/ui/actions/AppActions.js]: Swap conditions and avoid negation?
```js
// maybe also use stricter check like === undefined
Player.getSrc() ? PlayerActions.play() : PlayerActions.start();
```

File: src/main-process/main.js [hunk 5]
```diff
@@ -4,24 +4,26 @@ const path     = require('path');
...
-const TrayManager        = require('./tray'); // Manages Tray
-const ConfigManager      = require('./config'); // Handles config
-const PowerMonitor       = require('./power-monitor'); // Handle power events
-const IntegrationManager = require('./integration'); // Applies various integrations
-
-const app           = electron.app; // Module to control application life.
-const nativeImage   = electron.nativeImage;
-const BrowserWindow = electron.BrowserWindow; // Module to create native browser window.
-
+const IpcModule     = require('./modules/ipc'); // Manages IPC evens
```
Comment (YurySolovyov) [inline src/main-process/main.js]: typo: `events`

File: src/main-process/modules/dock-menu.js [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+        click: () => {
+          this.window.webContents.send(IPCR_PLAYER_ACTION, 'play');
+        },
+      },
+    ];
+
+    this.pauseToggle = [
+      {
+        label: 'Pause',
+        click: () => {
```
Comment (YurySolovyov) [inline src/main-process/modules/dock-menu.js]: can't we use short methods notation from ES6?
```js
{
  label: 'Pause',
  click() {
    this.window.webContents.send(IPCR_PLAYER_ACTION, 'pause');
  },
},
```

Comment (KeitIG) [reply src/main-process/modules/dock-menu.js]: Because the context is different, and `this` won't refer to the module itself but to a global window object.

**Comment by KeitIG** [comment]
I guess we're good to go for now
