### PR TITLE
Fix forgotten volume, playback and muted values on startup (fix #256, #263)

### LINKED ISSUE #256: Initial volume doesn't match volume bar
The volume seems to start out at a certain level, but the initial value for volume slider in the app doesn't match up with that value, so as soon as you move the slider, the music gets a lot louder.

### PR DESCRIPTION
**Pull request by KeitIG**

### CODE REVIEW

**Comment by YurySolovyov** [comment]
Does exponentiation always results in the max/min value at highest/lowest positions?
I wonder if it makes sense to add some kind of rounding to make 99.9 -> 100 and/or 0.01 -> 0, or whatever ranges we use.

**Comment by KeitIG** [comment]
@YurySolovyov it has a step of 0.01, we can increase it a bit if needed.

**Comment by YurySolovyov** [comment]
What I meant is: does dragging volume control to the full-right makes value become 100% ? or it is 99.9%?

**Comment by KeitIG** [comment]
ah, 100.

The input is in [0, 1] range.

```
Math.pow(0, 4) -> 0;
Math.pow(0.5, 4) -> 0.0625
Math.pow(1, 4) -> 1;
```

File: src/js/actions/PlayerActions.js [hunk 1]
```diff
@@ -55,16 +55,33 @@ const previous = () => {
...
 };
 
 const setVolume = (volume) => {
+
     if(!isNaN(parseFloat(volume)) && isFinite(volume)) {
 
-        Player.setAudioVolume(volume);
+        Player.setAudioVolume(Math.pow(volume, 4));
 
         app.config.set('audioVolume', Math.pow(volume, 4));
```
Comment (dkniffin) [inline src/js/actions/PlayerActions.js]: Since e're doing this twice, we should pull it out to a variable `exponentialVolume`, and use that in both spots.

Comment (dkniffin) [inline src/js/actions/PlayerActions.js]: Also, what do you think of refactoring this method to dispatch a `APP_PLAYER_VOLUME_CHANGE`, and put this logic into a reducer?

File: src/js/components/Header/VolumeControl.react.js [hunk 2]
```diff
@@ -54,7 +54,7 @@ export default class VolumeControl extends Component {
                            min={ 0 }
                            max={ 1 }
                            step={ 0.01 }
-                           defaultValue={ this.state.volume, 1 / 4 }
+                           defaultValue={ Math.pow(this.state.volume, 1 / 4) }
```
Comment (dkniffin) [inline src/js/components/Header/VolumeControl.react.js]: I might be wrong, but I believe this should go to line 24, so that line 51 is also updated correctly.

Comment (KeitIG) [inline src/js/components/Header/VolumeControl.react.js]: Fair

File: src/js/actions/PlayerActions.js (hunk 1 above)
Comment (KeitIG) [inline src/js/actions/PlayerActions.js]: > Also, what do you think of refactoring this method to dispatch a APP_PLAYER_VOLUME_CHANGE, and put this logic into a reducer?

No for multiple reasons:
- It wouldn't respect Flux pattern (the action update the config file)
- I think all the exponential stuff should always take place in the component, as it both receives and triggers values.

**Comment by KeitIG** [comment]
What are your questions about ?

File: src/js/components/Header/VolumeControl.react.js [hunk 3]
```diff
@@ -65,7 +65,7 @@ export default class VolumeControl extends Component {
 
     setVolume(e) {
         AppActions.player.setVolume(parseFloat(e.currentTarget.value));
-        this.setState({ volume: e.currentTarget.value });
+        this.setState({ volume: Math.pow(e.currentTarget.value, 4) });
```
Comment (dkniffin) [inline src/js/components/Header/VolumeControl.react.js]: Hmm. I think this commit re-breaks exponential volume control. This line will set the state to the correct value, but line 67 is the one that actually changes the audio volume, right?

**Comment by dkniffin** [comment]
Oh, I asked them in the review comments. You already addressed them with your commit.

**Comment by KeitIG** [comment]
I think it "should" be good now. woo.

File: src/js/components/Header/VolumeControl.react.js [hunk 4]
```diff
@@ -32,7 +32,7 @@ export default class VolumeControl extends Component {
     }
 
     getVolumeIcon(volume, muted) {
-        return muted || volume === 0 ? 'volume-off' : volume > 0.5 ? 'volume-up' : 'volume-down';
+        return muted || volume === 0 ? 'volume-off' : Math.pow(volume, 1 / 4) > 0.5 ? 'volume-up' : 'volume-down';
```
Comment (dkniffin) [inline src/js/components/Header/VolumeControl.react.js]: Ah, yea. These values are based on the linear values. Good catch.

One more knitpick. You can take it or leave it: since we're now doing this twice, I think it'd be good to pull it out into a function (`LinearizeVolume` or something) to DRY it up. It's probably also a good idea to do that with the `Math.pow` (`ExponentiateVolume` or something), so it's clear why we're doing it.

Comment (KeitIG) [inline src/js/components/Header/VolumeControl.react.js]: You don't see any problem if `LinearizeVolume` is in the component file as we're only using it here right ?

Comment (dkniffin) [inline src/js/components/Header/VolumeControl.react.js]: Yea, I think that makes sense. We've essentially just changed the component to an exponential slider, and any outside observers can just use the exponential value. They shouldn't have a need for the linear value.

However, I _could_ see another volume slider needing the linear volume value. eg: if we put a slider in the tray. But we can address that concern when we get to it.

Comment (KeitIG) [inline src/js/components/Header/VolumeControl.react.js]: Roger that

File: src/js/components/Header/VolumeControl.react.js [hunk 5]
```diff
@@ -21,7 +34,7 @@ export default class VolumeControl extends Component {
 
         this.state = {
             showVolume : false,
-            volume     : Math.pow(audio.volume, 1 / 4),
+            volume     : unsmoothifyVolume(audio.volume, 1 / 4),
```
Comment (dkniffin) [inline src/js/components/Header/VolumeControl.react.js]: I think this should be `unsmoothifyVolume(audio.volume, 4)`, since you're doing the `1 /` above

Comment (KeitIG) [inline src/js/components/Header/VolumeControl.react.js]: Wrong :p we're both wrong.

DARN.

I'll squash commits.

**Comment by KeitIG** [comment]
Are you able to accept the whole review?

**Comment by dkniffin** [comment]
I think I did accept the whole PR, but I don't count because I don't have write access. I think you need to make me a collaborator
