### PR TITLE
Play automatically plays the first song when the player is stopped

### LINKED ISSUE #223: Play button behavior when playerStatus is "stop"
We do not allow the possibility to play a selected track using the play button. It's not user friendly IMO. 

To reproduce it select a track and just click the play button. 
- Expected behavior : Play the sound 
- Actual behavior : nothing happen. (and the play button change to pause even with no song playing, maybe another issue?)

### LINKED ISSUE #226: Current song stays in buffer when flushing queue
When you flush the queue and clic next, the current song stop, right
But when you click on play, the last current song resumes instead of playing the first track of the playlist/song list

### PR DESCRIPTION
**Pull request by KeitIG**
Didn't really think this would be that easy.

fix #223 
fix #226

### CODE REVIEW

File: src/js/actions/PlayerActions.js [hunk 1]
```diff
@@ -54,8 +57,13 @@ const start = (_id) => {
     // TODO (y.solovyov | KeitIG): calling getState is a hack.
     const { tracks, tracksCursor } = store.getState();
     const queue = [...tracks[tracksCursor].sub];
+
+    if(queue.length === 0) return;
+
+    const trackId = _id || queue[0]._id;
```
Comment (YurySolovyov) [inline src/js/actions/PlayerActions.js]: is there a case where both will be absent?

Comment (KeitIG) [inline src/js/actions/PlayerActions.js]: Theoretically, no, but if so, the line 61 should have caught this case.
