### PR TITLE
Fix shuffle rollback when shuffle is already enabled during a SELECT_AND_PLAY

### LINKED ISSUE #348: Re-implement shuffle system
The shuffle system is buggy when you unshuffle from other views. Try to think about a way to re-implement it in a simpler way.

### PR DESCRIPTION
**Pull request by KeitIG**
More a bugfix than a re-implementation.

Fix #348

### CODE REVIEW

File: src/js/reducers/player.js [hunk 1]
```diff
@@ -130,6 +130,7 @@ export default (state = {}, payload) => {
                 };
             }
 
+            // Unshuffle the queue by restoring the initial queu
```
Comment (YurySolovyov) [inline src/js/reducers/player.js]: `queue`
